services:
  go-app2:
    container_name: go-app2
    image: francescoxx/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_db2 user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db2
  go_db2:
    container_name: go_db2
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}